---
# Deployment
apiVersion: apps/v1
kind:       Deployment
metadata:
  name: iconoflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iconoflix
  template:
    metadata:
      labels:
        app: iconoflix
    spec:
      containers:
      - name:  iconoflix
        image: quay.io/imhotepio/iconoflix:mem
        resources:
          requests:
            cpu:    100m
            memory: 50Mi
          limits:
            cpu:    200m
            memory: 70Mi
        ports:
        - name: http
          containerPort: 4000
---
# Service
apiVersion: v1
kind:       Service
metadata:
  name: iconoflix
spec:
  type: NodePort
  selector:
    app: iconoflix
  ports:
    - name: http
      port:     4000
      nodePort: 30400