---
# Deployment
apiVersion: apps/v1
kind:       Deployment
metadata:
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name:            hello
        image:           k8sland/probes-java:0.0.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu:    500m
            memory: 500Mi
          limits:
            cpu:    1
            memory: 800Mi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds:       10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 20
          periodSeconds:       5
        ports:
        - name:          http
          containerPort: 8080

---
# Service
kind:       Service
apiVersion: v1
metadata:
  name: hello
spec:
  type:  NodePort
  selector:
    app: hello
  ports:
    - port:     8080
      nodePort: 30800